name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Repository Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: GraalVM Setup
        uses: graalvm/setup-graalvm@bef4b0e916c7dd079bf60fb95d49139f67e32c5f
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Validate CHANGELOG
        run: ./gradlew validateChangelog


      - name: Run Tests
        run: ./gradlew test

      - name: Test Reporter
        uses: dorny/test-reporter@3eeb9fc888e82e8be2fb356bbeec2750231672bc
        if: always()
        with:
          name: JUnit Results
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit

  build-artifacts:
    name: Build Artifacts ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: ybymo-linux-amd64
            binary: ybymo-cli/build/native/nativeCompile/ybymo
            bin_name: ybymo

          - os: macos-latest
            artifact: ybymo-macos-arm64
            binary: ybymo-cli/build/native/nativeCompile/ybymo
            bin_name: ybymo

          - os: windows-latest
            artifact: ybymo-windows-amd64
            binary: ybymo-cli/build/native/nativeCompile/ybymo.exe
            bin_name: ybymo.exe

    steps:
      - name: Repository Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: GraalVM Setup
        uses: graalvm/setup-graalvm@bef4b0e916c7dd079bf60fb95d49139f67e32c5f
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradlew Permissions
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build Binary
        run: ./gradlew :ybymo-cli:nativeCompile

      - name: Prepare Artifact
        shell: bash
        run: |
          cp ${{ matrix.binary }} ${{ matrix.bin_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.bin_name }}
          if-no-files-found: error
